#ifndef PRINTERS_H
#define PRINTERS_H

#define PRINTER_UNKNOWN 0

// *** MKP1
#define PRINTER_MKP1    400
#define PRINTER_MKP1_NAME  "MKP1"
#define PRINTER_MKP1_MMU2 40200
#define PRINTER_MKP1_MMU2_NAME "MKP1MMU2"

#endif //PRINTERS_H
